version: "3.9"

services:
  web:
    build: .
    container_name: draftosaurus_web
    ports:
      - "8080:80"
    volumes:
      # volumen llamado 'proyecto' donde se guardará tu app
      - proyecto:/var/www/html/draftosaurus/public
    depends_on:
      - db
    networks:
      - draftosaurus_net

  db:
    image: mariadb:11
    container_name: draftosaurus_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: draftosaurus_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    volumes:
      # volumen llamado 'mariadb' donde se guardarán los datos del servidor SQL
      - mariadb:/var/lib/mysql
    networks:
      - draftosaurus_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: draftosaurus_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8081:80"
    networks:
      - draftosaurus_net

# Definición de los volúmenes
volumes:
  proyecto:
  mariadb:

# Red interna para conectar los contenedores
networks:
  draftosaurus_net:
    driver: bridge
