version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto
    ports:
      - "8080:80"
    depends_on:
      - database

  database:
    image: mariadb
    container_name: proyectodb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: draftosaurus_db
      MYSQL_USER: root
      MYSQL_PASSWORD: drafto123
    ports:
      - "8082:3306"
    volumes:
      - maria-db:/var/lib/mysql
      - ./others/bd.sql:/docker-entrypoint-initdb.d/bd.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: draftosaurus_phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: drafto123
    ports:
      - "8081:80"

# Definición de los volúmenes
volumes:
  draftoapp:
  maria-db:
